<a href="https://colab.research.google.com/github/GiorgosLyberis/mcda/blob/main/Methods%20For%20Statistical%20Data%20Analysis/Lab_8/Lab_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
data<-matrix(c(4,11,2,38),2,2,byrow=T)
data
fisher.test(data)
(4*38)/(2*11)
chisq.test(data)

[,1] [,2]
[1,] 4    11  
[2,] 2    38


	Fisher's Exact Test for Count Data

data:  data
p-value = 0.04104
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.8242789 82.0421661
sample estimates:
odds ratio 
  6.607341 


[1] 6.909091

Warning message in chisq.test(data):
“Chi-squared approximation may be incorrect”



	Pearson's Chi-squared test with Yates' continuity correction

data:  data
X-squared = 3.2758, df = 1, p-value = 0.07031


In [3]:
data<-matrix(c(4,0,0,4),2,2,byrow=T)
data
fisher.test(data)
chisq.test(data)

[,1] [,2]
[1,] 4    0   
[2,] 0    4


	Fisher's Exact Test for Count Data

data:  data
p-value = 0.02857
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 1.339059      Inf
sample estimates:
odds ratio 
       Inf 


Warning message in chisq.test(data):
“Chi-squared approximation may be incorrect”



	Pearson's Chi-squared test with Yates' continuity correction

data:  data
X-squared = 4.5, df = 1, p-value = 0.03389


In [4]:
## 6th example in Mehta & Patel's JASA paper
MP6 <- rbind(
        c(1,2,2,1,1,0,1),
        c(2,0,0,2,3,0,0),
        c(0,1,1,1,2,7,3),
        c(1,1,2,0,0,0,1),
        c(0,1,1,1,1,0,0))
fisher.test(MP6)
# Exactly the same p-value, as Cochran's conditions are never met:
fisher.test(MP6, hybrid=TRUE)


	Fisher's Exact Test for Count Data

data:  MP6
p-value = 0.03929
alternative hypothesis: two.sided



	Fisher's Exact Test for Count Data hybrid using asym.chisq. iff (exp=5,
	perc=80, Emin=1)

data:  MP6
p-value = 0.03929
alternative hypothesis: two.sided


In [5]:
# Mantel-Haenszel

mh.array<-array(c(4,12,9,34,4,34,6,33,7,6,2,7,5,59,
5,56,7,22,7,69,5,41,6,80,3,8,6,72,4,1,8,20,7,77,2,
38,4,20,6,70,1,16,8,76,4,10,10,91,9,27,18,118,3,35,
5,45,9,69,5,20,2,3,3,12,6,45, 1,31,14,12,10,70,15,
43,15,129),c(2,2,19))
mh.array

mantelhaen.test(mh.array)
mantelhaen.test(mh.array,correct=F)

, , 1

     [,1] [,2]
[1,]    4    9
[2,]   12   34

, , 2

     [,1] [,2]
[1,]    4    6
[2,]   34   33

, , 3

     [,1] [,2]
[1,]    7    2
[2,]    6    7

, , 4

     [,1] [,2]
[1,]    5    5
[2,]   59   56

, , 5

     [,1] [,2]
[1,]    7    7
[2,]   22   69

, , 6

     [,1] [,2]
[1,]    5    6
[2,]   41   80

, , 7

     [,1] [,2]
[1,]    3    6
[2,]    8   72

, , 8

     [,1] [,2]
[1,]    4    8
[2,]    1   20

, , 9

     [,1] [,2]
[1,]    7    2
[2,]   77   38

, , 10

     [,1] [,2]
[1,]    4    6
[2,]   20   70

, , 11

     [,1] [,2]
[1,]    1    8
[2,]   16   76

, , 12

     [,1] [,2]
[1,]    4   10
[2,]   10   91

, , 13

     [,1] [,2]
[1,]    9   18
[2,]   27  118

, , 14

     [,1] [,2]
[1,]    3    5
[2,]   35   45

, , 15

     [,1] [,2]
[1,]    9    5
[2,]   69   20

, , 16

     [,1] [,2]
[1,]    2    3
[2,]    3   12

, , 17

     [,1] [,2]
[1,]    6    1
[2,]   45   31

, , 18

     [,1] [,2]
[1,]   14   10
[2,]   12   70

, , 19

     [,1] [,2]
[1,]   15   15
[2,]   43  129


	Mantel-Haenszel chi-squared test with continuity correction

data:  mh.array
Mantel-Haenszel X-squared = 25.188, df = 1, p-value = 5.201e-07
alternative hypothesis: true common odds ratio is not equal to 1
95 percent confidence interval:
 1.551143 2.795841
sample estimates:
common odds ratio 
         2.082486 



	Mantel-Haenszel chi-squared test without continuity correction

data:  mh.array
Mantel-Haenszel X-squared = 25.994, df = 1, p-value = 3.425e-07
alternative hypothesis: true common odds ratio is not equal to 1
95 percent confidence interval:
 1.551143 2.795841
sample estimates:
common odds ratio 
         2.082486 


In [7]:
data <-matrix(c(21, 2, 9, 12),nrow = 2,
        dimnames = list("Control" = c("Fail", "Pass"),
                        "Test" = c("Fail", "Pass")))
data
mcnemar.test(data)
(abs(9-2)-1)^2/(9+2); 1-pchisq((abs(9-2)-1)^2/(9+2),df=1)
prop.test(9,9+2,p=1/2)

mcnemar.test(data,correct=FALSE)
(9-2)^2/(9+2)
1-pchisq((9-2)^2/(9+2),df=1)
prop.test(9,9+2,p=1/2,correct=FALSE)

install.packages("exact2x2")

library(exact2x2)
help(exact2x2)
mcnemar.exact(data)

Test
Control Fail Pass
   Fail 21    9  
   Pass  2   12


	McNemar's Chi-squared test with continuity correction

data:  data
McNemar's chi-squared = 3.2727, df = 1, p-value = 0.07044


[1] 3.272727

[1] 0.07044043


	1-sample proportions test with continuity correction

data:  9 out of 9 + 2, null probability 1/2
X-squared = 3.2727, df = 1, p-value = 0.07044
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.4775496 0.9678614
sample estimates:
        p 
0.8181818 



	McNemar's Chi-squared test

data:  data
McNemar's chi-squared = 4.4545, df = 1, p-value = 0.03481


[1] 4.454545

[1] 0.03480848


	1-sample proportions test without continuity correction

data:  9 out of 9 + 2, null probability 1/2
X-squared = 4.4545, df = 1, p-value = 0.03481
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.5230194 0.9486323
sample estimates:
        p 
0.8181818 


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘exactci’, ‘ssanv’


Loading required package: exactci

Loading required package: ssanv

Loading required package: testthat




	Exact McNemar test (with central confidence intervals)

data:  data
b = 9, c = 2, p-value = 0.06543
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.9314123 42.7997159
sample estimates:
odds ratio 
       4.5 


In [8]:
data <-matrix(c(3, 2, 9, 1),nrow = 2,
        dimnames = list("Control" = c("Fail", "Pass"),
                        "Test" = c("Fail", "Pass")))
data
mcnemar.test(data)
mcnemar.exact(data)
binom.test(9,9+2,p=1/2)

Test
Control Fail Pass
   Fail 3    9   
   Pass 2    1


	McNemar's Chi-squared test with continuity correction

data:  data
McNemar's chi-squared = 3.2727, df = 1, p-value = 0.07044



	Exact McNemar test (with central confidence intervals)

data:  data
b = 9, c = 2, p-value = 0.06543
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.9314123 42.7997159
sample estimates:
odds ratio 
       4.5 



	Exact binomial test

data:  9 and 9 + 2
number of successes = 9, number of trials = 11, p-value = 0.06543
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.4822441 0.9771688
sample estimates:
probability of success 
             0.8181818 


In [9]:
data <-matrix(c(15, 5, 4, 3, 7, 8, 9, 20, 60),nrow = 3,
        dimnames = list("Control" = c("Rodos", "Mykonos", "Santorini"),
                        "Test" = c("Rodos", "Mykonos", "Santorini")))
data
mcnemar.test(data,correct=FALSE)
(5-3)^2/(5+3)+(9-4)^2/(9+4)+(8-20)^2/(8+20)
prop.test(c(5,9,8),c(8,12,28),p=c(1/2,1/2,1/2),correct=FALSE)

Test
Control     Rodos Mykonos Santorini
  Rodos     15    3        9       
  Mykonos    5    7       20       
  Santorini  4    8       60


	McNemar's Chi-squared test

data:  data
McNemar's chi-squared = 7.5659, df = 3, p-value = 0.05589


[1] 7.565934

Warning message in prop.test(c(5, 9, 8), c(8, 12, 28), p = c(1/2, 1/2, 1/2), correct = FALSE):
“Chi-squared approximation may be incorrect”



	3-sample test for given proportions without continuity correction

data:  c(5, 9, 8) out of c(8, 12, 28), null probabilities c(1/2, 1/2, 1/2)
X-squared = 8.6429, df = 3, p-value = 0.03444
alternative hypothesis: two.sided
null values:
prop 1 prop 2 prop 3 
   0.5    0.5    0.5 
sample estimates:
   prop 1    prop 2    prop 3 
0.6250000 0.7500000 0.2857143 
